//*************************************************************
//  Author    : Fukutani, Kei
//  File Name : R.java
//  Date      : 9/28/14
//  Objective : This file indicates where all the UI components
//              are in the memory. 
//*************************************************************

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.cs311d.demofragmentf1;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int action_settings=0x7f08000c;
        public static final int btn_bmw=0x7f080007;
        public static final int btn_corvett=0x7f080005;
        public static final int btn_fiat=0x7f080002;
        public static final int btn_honda=0x7f080004;
        public static final int btn_kia=0x7f080006;
        public static final int btn_power=0x7f080008;
        public static final int btn_price=0x7f080003;
        public static final int frag1=0x7f080000;
        public static final int frag2=0x7f080001;
        public static final int tv1=0x7f080009;
        public static final int tv2_car=0x7f08000a;
        public static final int tv2_value=0x7f08000b;
    }
    public static final class layout {
        public static final int activity_demo_fragment_f1=0x7f030000;
        public static final int frag1=0x7f030001;
        public static final int frag2=0x7f030002;
    }
    public static final class menu {
        public static final int demo_fragment_f1=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int btn_bmw=0x7f050002;
        public static final int btn_corvett=0x7f050003;
        public static final int btn_fiat=0x7f050004;
        public static final int btn_honda=0x7f050005;
        public static final int btn_kia=0x7f050006;
        public static final int btn_power=0x7f050007;
        public static final int btn_price=0x7f050008;
        public static final int hello_blank_fragment=0x7f050009;
        public static final int hello_world=0x7f05000a;
        public static final int title_activity_show_info=0x7f05000b;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
}
