//*************************************************************
//  Author    : Kei Fukutani
//  File Name : R.java
//  Date      : 4/22/14
//  Objective : This file indicates where all the UI components
//              are in the memory. 
//*************************************************************

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.usstatesgame2;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int action_settings=0x7f080044;
        public static final int btn_done=0x7f080020;
        public static final int btn_home=0x7f080043;
        public static final int btn_play=0x7f080003;
        public static final int btn_replay=0x7f08002b;
        public static final int btn_score=0x7f080002;
        public static final int et=0x7f080001;
        public static final int et_q1=0x7f080015;
        public static final int et_q10=0x7f08001e;
        public static final int et_q2=0x7f080016;
        public static final int et_q3=0x7f080017;
        public static final int et_q4=0x7f080018;
        public static final int et_q5=0x7f080019;
        public static final int et_q6=0x7f08001a;
        public static final int et_q7=0x7f08001b;
        public static final int et_q8=0x7f08001c;
        public static final int et_q9=0x7f08001d;
        public static final int textView1=0x7f080000;
        public static final int text_bg=0x7f080004;
        public static final int text_capitals=0x7f080006;
        public static final int text_capitals2=0x7f08000e;
        public static final int text_n1=0x7f08002c;
        public static final int text_n10=0x7f080036;
        public static final int text_n11=0x7f080041;
        public static final int text_n2=0x7f08002e;
        public static final int text_n3=0x7f08002f;
        public static final int text_n4=0x7f080030;
        public static final int text_n5=0x7f080031;
        public static final int text_n6=0x7f080032;
        public static final int text_n7=0x7f080033;
        public static final int text_n8=0x7f080034;
        public static final int text_n9=0x7f080035;
        public static final int text_name=0x7f080005;
        public static final int text_points=0x7f08001f;
        public static final int text_q1=0x7f080009;
        public static final int text_q10=0x7f080014;
        public static final int text_q2=0x7f08000a;
        public static final int text_q3=0x7f08000b;
        public static final int text_q4=0x7f08000c;
        public static final int text_q5=0x7f08000d;
        public static final int text_q6=0x7f080010;
        public static final int text_q7=0x7f080011;
        public static final int text_q8=0x7f080012;
        public static final int text_q9=0x7f080013;
        public static final int text_result1=0x7f080021;
        public static final int text_result10=0x7f08002a;
        public static final int text_result2=0x7f080022;
        public static final int text_result3=0x7f080023;
        public static final int text_result4=0x7f080024;
        public static final int text_result5=0x7f080025;
        public static final int text_result6=0x7f080026;
        public static final int text_result7=0x7f080027;
        public static final int text_result8=0x7f080028;
        public static final int text_result9=0x7f080029;
        public static final int text_s1=0x7f080037;
        public static final int text_s10=0x7f080040;
        public static final int text_s11=0x7f080042;
        public static final int text_s2=0x7f080038;
        public static final int text_s3=0x7f080039;
        public static final int text_s4=0x7f08003a;
        public static final int text_s5=0x7f08003b;
        public static final int text_s6=0x7f08003c;
        public static final int text_s7=0x7f08003d;
        public static final int text_s8=0x7f08003e;
        public static final int text_s9=0x7f08003f;
        public static final int text_states=0x7f080007;
        public static final int text_states2=0x7f08000f;
        public static final int text_title=0x7f08002d;
        public static final int user_name=0x7f080008;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int activity_quiz_activity2=0x7f030001;
        public static final int activity_score=0x7f030002;
    }
    public static final class menu {
        public static final int main=0x7f070000;
        public static final int quiz_activity2=0x7f070001;
        public static final int score=0x7f070002;
    }
    public static final class string {
        public static final int action_settings=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int btn_done=0x7f05000c;
        public static final int btn_play=0x7f050004;
        public static final int btn_score=0x7f050005;
        public static final int hello_world=0x7f050002;
        public static final int text_capitals=0x7f05000b;
        public static final int text_hint=0x7f050006;
        public static final int text_name=0x7f050008;
        public static final int text_points=0x7f05000e;
        public static final int text_states=0x7f05000a;
        public static final int text_title=0x7f050003;
        public static final int title_activity_quiz=0x7f050007;
        public static final int title_activity_quiz_activity2=0x7f05000d;
        public static final int title_activity_score=0x7f05000f;
        public static final int user_name=0x7f050009;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
