//*************************************************************
//  Author    : Fukutani, Kei
//  File Name : R.java
//  Date      : 12/14/14
//  Objective : This file indicates where all the UI components
//              are in the memory. 
//*************************************************************

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.cs311d.demoanim;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int anim1=0x7f020000;
        public static final int anim2=0x7f020001;
        public static final int anim3=0x7f020002;
        public static final int anim4=0x7f020003;
        public static final int anim5=0x7f020004;
        public static final int anim6=0x7f020005;
        public static final int anim7=0x7f020006;
        public static final int anim8=0x7f020007;
        public static final int animp1=0x7f020008;
        public static final int animp2=0x7f020009;
        public static final int animp3=0x7f02000a;
        public static final int animp4=0x7f02000b;
        public static final int animp5=0x7f02000c;
        public static final int ic_launcher=0x7f02000d;
    }
    public static final class id {
        public static final int action_settings=0x7f080004;
        public static final int iv=0x7f080000;
        public static final int sbar=0x7f080001;
        public static final int tglbtn=0x7f080003;
        public static final int tv=0x7f080002;
    }
    public static final class layout {
        public static final int activity_demo_anim=0x7f030000;
    }
    public static final class menu {
        public static final int demo_anim=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int hello_world=0x7f050002;
    }
    public static final class style {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
}
